apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app1-chart.fullname" . }}-config
  labels:
    {{ include "app1-chart.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config | nindent 2 }}
